const providers = {
  PROVIDE_REQUEST: '@provider/PROVIDE_REQUEST',
  PROVIDE_DATETIME_REQUEST: '@provider/PROVIDE_DATETIME_REQUEST',
  PROVIDE_SEND_SCHEDULE: '@provider/PROVIDE_SEND_SCHEDULE',
  PROVIDE_SUCCESS: '@provider/PROVIDE_SUCCESS',
  PROVIDE_DATETIME_SUCCESS: '@provider/PROVIDE_DATETIME_SUCCESS',
};

export default providers;
