const notifications = {
  NOTIFICATION_REQUEST: '@notification/NOTIFICATION_REQUEST',
  NOTIFICATION_REQUEST_UPDATE: '@notification/NOTIFICATION_REQUEST_UPDATE',
  NOTIFICATION_SUCCESS_UPDATE: '@notification/NOTIFICATION_SUCCESS_UPDATE',
  NOTIFICATION_SUCCESS: '@notification/NOTIFICATION_SUCCESS',
};

export default notifications;
