const appointment = {
  APPOINTMENT_REQUEST: '@appointment/APPOINTMENT_REQUEST',
  APPOINTMENT_SUCCESS: '@appointment/APPOINTMENT_SUCCESS',
  APPOINTMENT_DELETE_REQUEST: '@appointment/APPOINTMENT_DELETE_REQUEST',
  APPOINTMENT_DELETE_SUCCESS: '@appointment/APPOINTMENT_DELETE_SUCCESS',
};

export default appointment;
